### ISSUE TITLE
module 'customtkinter' has no attribute 'set_appearance_mode'

### ISSUE THREAD

**Issue by roelvanderzee** [TomSchimansky/CustomTkinter#1474]
When I update to 5.1.2, and run the example code below, I get the error "module 'customtkinter' has no attribute 'set_appearance_mode'". This was NOT the case when I had 5.0.3 installed

import tkinter
import customtkinter
customtkinter.set_appearance_mode("System")  # Modes: system (default), light, dark
customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green
app = customtkinter.CTk()  # create CTk window like you do with the Tk window
app.geometry("400x240")
def button_function():
       print("button pressed")

button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)
app.mainloop()

**Comment by mayank-crypto-byte** [comment]
try using 

`customtkinter._set_appearance_mode("System")`

it worked for me

**Comment by avalon60** [comment]
> try using
> 
> `customtkinter._set_appearance_mode("System")`
> 
> it worked for me

The leading underscore indicates that it's a private method, so should only be used internally to customtkinter. This looks like a bug. The wiki publishes the method without underscore - strange.

**Comment by TomSchimansky** [comment]
The method is there, you probably created a file called customtkinter.py next to your .py file?
