### ISSUE TITLE
Does not work with Python 3.7

### ISSUE THREAD

**Issue by roelvanderzee** [TomSchimansky/CustomTkinter#737]
CustomTkinter does not work with Python 3.7

**Comment by Akascape** [comment]
So upgrade your python version.

**Comment by TomSchimansky** [comment]
You have to tell me what's the problem, otherwise I can't help. Normally it should work on python 3.7.

**Comment by roelvanderzee** [comment]
I get the message
cannot import name 'Literal' from 'typing' (C:\Users\921040\AppData\Local\Continuum\anaconda3\lib\typing.py)

I think It has to be

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal

**Comment by TomSchimansky** [comment]
Ok didn't thought of this, I will fix this with the next version.
